const POSTER_THEMES = [
  {
    id: 'default',
    name: '默认',
    buildHTMLName: 'buildDefaultPosterHTML',
    cssVars: {
      '--poster-bg': '#23242a',
      '--poster-title-color': '#45f3ff',
      '--poster-title-shadow': '0 0 10px rgba(69, 243, 255, 0.5)',
      '--poster-time-color': '#8f8f8f',
      '--poster-rank-color': '#ffffff',
      '--poster-score-color': '#45f3ff',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.05)',
      '--poster-item-border': 'transparent',
      '--poster-item-shadow': 'none',
      '--poster-gold': '#ffd700',
      '--poster-silver': '#c0c0c0',
      '--poster-bronze': '#cd7f32',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(255, 215, 0, 0.1), transparent)',
      '--poster-footer-color': '#8f8f8f',
      '--poster-footer-border': 'rgba(255, 255, 255, 0.1)',
      '--poster-total-color': '#8f8f8f',
      '--poster-total-value-color': '#45f3ff',
      '--poster-card-radius': '8px',
      '--poster-font-title': "'ZCOOL KuaiLe', cursive",
    },
    defaultColors: {
      bgColor: '#23242a',
      titleColor: '#45f3ff',
      rankColor: '#ffffff',
      scoreColor: '#45f3ff',
    },
  },
  {
    id: 'plain',
    name: '极简',
    cssVars: {},
    isPlain: true,
    defaultColors: {
      bgColor: '#ffffff',
      titleColor: '#333333',
      rankColor: '#333333',
      scoreColor: '#555555',
    },
  },
  {
    id: 'elegant-blue',
    name: '白兰',
    buildHTMLName: 'buildElegantBluePosterHTML',
    cssVars: {
      '--poster-bg': 'linear-gradient(135deg, #f0f4f8, #e1e8f0)',
      '--poster-title-color': '#4a607a',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#7a8a9a',
      '--poster-rank-color': '#2d3748',
      '--poster-score-color': '#3b6d8c',
      '--poster-item-bg': '#ffffff',
      '--poster-item-border': 'rgba(74, 96, 122, 0.18)',
      '--poster-item-shadow': '0 2px 10px rgba(0, 0, 0, 0.08)',
      '--poster-gold': '#b8860b',
      '--poster-silver': '#708090',
      '--poster-bronze': '#8b4513',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(184, 134, 11, 0.08), transparent)',
      '--poster-footer-color': '#7a8a9a',
      '--poster-footer-border': 'rgba(0, 0, 0, 0.1)',
      '--poster-total-color': '#7a8a9a',
      '--poster-total-value-color': '#4a607a',
      '--poster-card-radius': '10px',
      '--poster-font-title': "'Noto Sans SC', sans-serif",
    },
    defaultColors: {
      bgColor: '#f0f4f8',
      titleColor: '#4a607a',
      rankColor: '#2d3748',
      scoreColor: '#3b6d8c',
    },
  },
  {
    id: 'noble-gold',
    name: '雅贵',
    buildHTMLName: 'buildNobleGoldPosterHTML',
    cssVars: {
      '--poster-bg': '#1c2230',
      '--poster-title-color': '#f6d365',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#8a8a9a',
      '--poster-rank-color': '#e8e0d0',
      '--poster-score-color': '#ffd700',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.03)',
      '--poster-item-border': 'rgba(255, 215, 0, 0.2)',
      '--poster-item-shadow': '0 2px 12px rgba(0, 0, 0, 0.3)',
      '--poster-gold': '#ffd700',
      '--poster-silver': '#c0c0c0',
      '--poster-bronze': '#cd7f32',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(255, 215, 0, 0.08), transparent)',
      '--poster-footer-color': '#8a8a9a',
      '--poster-footer-border': 'rgba(255, 215, 0, 0.15)',
      '--poster-total-color': '#8a8a9a',
      '--poster-total-value-color': '#ffd700',
      '--poster-card-radius': '8px',
      '--poster-font-title': "'ZCOOL KuaiLe', cursive",
    },
    defaultColors: {
      bgColor: '#1c2230',
      titleColor: '#f6d365',
      rankColor: '#e8e0d0',
      scoreColor: '#ffd700',
    },
  },
  {
    id: 'sakura-pink',
    name: '樱花柔粉',
    buildHTMLName: 'buildSakuraPinkPosterHTML',
    cssVars: {
      '--poster-bg': 'linear-gradient(135deg, #fff5f7, #fce4ec, #f8e8f0)',
      '--poster-title-color': '#9c5f75',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#a88a95',
      '--poster-rank-color': '#4a3035',
      '--poster-score-color': '#b55a70',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.92)',
      '--poster-item-border': 'rgba(156, 95, 117, 0.2)',
      '--poster-item-shadow': '0 2px 10px rgba(156, 95, 117, 0.12)',
      '--poster-gold': '#d4a574',
      '--poster-silver': '#b8a9c9',
      '--poster-bronze': '#c48b9f',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(212, 165, 116, 0.08), transparent)',
      '--poster-footer-color': '#a88a95',
      '--poster-footer-border': 'rgba(156, 95, 117, 0.2)',
      '--poster-total-color': '#a88a95',
      '--poster-total-value-color': '#9c5f75',
      '--poster-card-radius': '12px',
      '--poster-font-title': "'Noto Sans SC', sans-serif",
    },
    defaultColors: {
      bgColor: '#fff5f7',
      titleColor: '#9c5f75',
      rankColor: '#4a3035',
      scoreColor: '#b55a70',
    },
  },
  {
    id: 'matcha-latte',
    name: '抹茶拿铁',
    buildHTMLName: 'buildMatchaLattePosterHTML',
    cssVars: {
      '--poster-bg': 'linear-gradient(135deg, #f5f0e8, #e8e0d0, #f0ebe0)',
      '--poster-title-color': '#4a5c35',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#7a8a6b',
      '--poster-rank-color': '#3a3025',
      '--poster-score-color': '#4f6638',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.92)',
      '--poster-item-border': 'rgba(74, 92, 53, 0.18)',
      '--poster-item-shadow': '0 2px 8px rgba(74, 92, 53, 0.1)',
      '--poster-gold': '#b8860b',
      '--poster-silver': '#9e8e7e',
      '--poster-bronze': '#8b7355',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(184, 134, 11, 0.06), transparent)',
      '--poster-footer-color': '#7a8a6b',
      '--poster-footer-border': 'rgba(74, 92, 53, 0.18)',
      '--poster-total-color': '#7a8a6b',
      '--poster-total-value-color': '#4a5c35',
      '--poster-card-radius': '10px',
      '--poster-font-title': "'Noto Sans SC', sans-serif",
    },
    defaultColors: {
      bgColor: '#f5f0e8',
      titleColor: '#4a5c35',
      rankColor: '#3a3025',
      scoreColor: '#4f6638',
    },
  },
  {
    id: 'haze-blue',
    name: '雾霾蓝',
    buildHTMLName: 'buildHazeBluePosterHTML',
    cssVars: {
      '--poster-bg': 'linear-gradient(135deg, #e8eef4, #d4e0ed, #e0e8f0)',
      '--poster-title-color': '#3d5a78',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#7a90a8',
      '--poster-rank-color': '#2c4358',
      '--poster-score-color': '#3a6a8f',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.92)',
      '--poster-item-border': 'rgba(61, 90, 120, 0.18)',
      '--poster-item-shadow': '0 2px 10px rgba(61, 90, 120, 0.1)',
      '--poster-gold': '#b8860b',
      '--poster-silver': '#7a9bb5',
      '--poster-bronze': '#8b7355',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(184, 134, 11, 0.06), transparent)',
      '--poster-footer-color': '#7a90a8',
      '--poster-footer-border': 'rgba(61, 90, 120, 0.18)',
      '--poster-total-color': '#7a90a8',
      '--poster-total-value-color': '#3d5a78',
      '--poster-card-radius': '10px',
      '--poster-font-title': "'Noto Sans SC', sans-serif",
    },
    defaultColors: {
      bgColor: '#e8eef4',
      titleColor: '#3d5a78',
      rankColor: '#2c4358',
      scoreColor: '#3a6a8f',
    },
  },
  {
    id: 'cream-yellow',
    name: '奶油暖黄',
    buildHTMLName: 'buildCreamYellowPosterHTML',
    cssVars: {
      '--poster-bg': 'linear-gradient(135deg, #fef9ef, #fdf3e0, #fef5ea)',
      '--poster-title-color': '#8f6a2e',
      '--poster-title-shadow': 'none',
      '--poster-time-color': '#9a8565',
      '--poster-rank-color': '#4a3a2a',
      '--poster-score-color': '#8f6a2e',
      '--poster-item-bg': 'rgba(255, 255, 255, 0.92)',
      '--poster-item-border': 'rgba(143, 106, 46, 0.18)',
      '--poster-item-shadow': '0 2px 10px rgba(143, 106, 46, 0.1)',
      '--poster-gold': '#d4a44a',
      '--poster-silver': '#b8a898',
      '--poster-bronze': '#a88868',
      '--poster-top1-bg': 'linear-gradient(90deg, rgba(212, 164, 74, 0.08), transparent)',
      '--poster-footer-color': '#9a8565',
      '--poster-footer-border': 'rgba(143, 106, 46, 0.18)',
      '--poster-total-color': '#9a8565',
      '--poster-total-value-color': '#8f6a2e',
      '--poster-card-radius': '10px',
      '--poster-font-title': "'Noto Sans SC', sans-serif",
    },
    defaultColors: {
      bgColor: '#fef9ef',
      titleColor: '#8f6a2e',
      rankColor: '#4a3a2a',
      scoreColor: '#8f6a2e',
    },
  },
];

function getThemeConfig(themeId) {
  return POSTER_THEMES.find(t => t.id === themeId) || POSTER_THEMES[0];
}

function applyThemeToPosterBox(themeConfig) {
  const posterBox = document.getElementById('posterBox');
  posterBox.style.cssText = '';
  Object.entries(themeConfig.cssVars).forEach(([prop, value]) => {
    posterBox.style.setProperty(prop, value);
  });
}

function populateThemeSelect() {
  const select = document.getElementById('posterThemeSelect');
  if (!select) return;
  select.innerHTML = '';
  POSTER_THEMES.forEach(theme => {
    const option = document.createElement('option');
    option.value = theme.id;
    option.textContent = theme.name;
    select.appendChild(option);
  });
}
